version: '3.8'

services:
  nextjs-app:
    build:
      network: host
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public

