
# Use the official Node.js LTS image as the base image
FROM node:21-alpine3.18

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies for development
RUN npm install --verbose

# Copy the rest of the application code
COPY . .

# Expose the port that Next.js uses (default is 3000)
EXPOSE 3000

# Start the application in development mode
CMD ["npm", "run", "dev"]

